package za.co.qsnext.employeemanagement.payroll;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

public interface PayrollLineItemRepository extends JpaRepository<PayrollLineItem, UUID> {

    List<PayrollLineItem> findByPayrollRunEntryId(UUID payrollRunEntryId);

    /**
     * Sums only the "OVERTIME" earning line items generated by
     * {@code PayrollRunService} for runs whose pay period falls within
     * the given range - manual overtime-coded adjustments included.
     */
    @Query("""
            select coalesce(sum(li.amount), 0)
            from PayrollLineItem li
            where li.type = 'EARNING'
            and li.code = 'OVERTIME'
            and li.payrollRunEntryId in (
                select e.id from PayrollRunEntry e
                where e.payrollRunId in (
                    select r.id from PayrollRun r
                    where r.payPeriodId in (
                        select p.id from PayPeriod p
                        where p.startDate >= :from and p.endDate <= :to
                    )
                )
            )
            """)
    BigDecimal sumOvertimeAmountForPeriod(@Param("from") LocalDate from, @Param("to") LocalDate to);
}
